### ISSUE TITLE
Error while invoking rfpy_calc in terminal

### ISSUE THREAD

**Issue by dip16gphy** [paudetseis/RfPy#31]
I have this error while calculating RF in terminal.
Please help.

Thanks.
![image](https://user-images.githubusercontent.com/101346054/158256106-c152de53-de9d-4cf0-804a-f80d1afb8946.png)
![image](https://user-images.githubusercontent.com/101346054/158256162-e4a8dce5-65bb-46be-9a9b-f14d82d2bcbc.png)

**Comment by wsja** [comment]
This looks like an obspy problem. Can you please open, in the same conda environment, a python console and post the output of:
```
import obspy
obspy.__version__
```

**Comment by wsja** [comment]
@paudetseis Or might this have to do with `MMPY.pkl` being platform dependent? I have some commits for `stdb` to read `.csv` instead, which would likely solve the problem and would also be more transparent. I'll open a pull request for `stdb` and ask @schaefferaj if he can include it.

**Comment by dip16gphy** [comment]
> This looks like an obspy problem. Can you please open, in the same conda environment, a python console and post the output of:
> 
> ```
> import obspy
> obspy.__version__



obspy version is 1.3.0.

**Comment by paudetseis** [comment]
hmm, the exception is raised by the `client` package, and not `obspy`. I have never seen this exception before, so I'm not sure how to fix it. 

Can you type, in a terminal:
`conda activate rfpy`
`conda list --explicit > spec-file.txt`

and share the file here?

**Comment by dip16gphy** [comment]
> hmm, the exception is raised by the `client` package, and not `obspy`. I have never seen this exception before, so I'm not sure how to fix it.
> 
> Can you type, in a terminal: `conda activate rfpy` `conda list --explicit > spec-file.txt`
> 
> and share the file here?


Yes.. 
[spec-file.txt](https://github.com/paudetseis/RfPy/files/8254493/spec-file.txt)

**Comment by dip16gphy** [comment]
> hmm, the exception is raised by the `client` package, and not `obspy`. I have never seen this exception before, so I'm not sure how to fix it.
> 
> Can you type, in a terminal: `conda activate rfpy` `conda list --explicit > spec-file.txt`
> 
> and share the file here?

Do we have any solution to this error now?
I want to know if the command runs in your terminal too?
Please help.

**Comment by paudetseis** [comment]
Please note that we are not always able to address these issues quickly, especially if they are platform dependent. I will try to look into it as soon as I can.

**Comment by wsja** [comment]
I assume that the the provided `MMPY.pkl` does not work on your Windows platform.

If you have [`stdb`](https://github.com/schaefferaj/StDb) installed (you should, because it is a dependency of RfPy), you can recreate `MMPY.pkl` by typing on the command line:

`./query_fdsn_stdb.py -N NY -S MMPY -C HH? MMPY`

Can you try this and see if it solves your problem?

**Comment by wsja** [comment]
The script is running for me. I also tested the obspy call in question with the obspy version you are using (1.3.0):

`event_client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6)`

and it worked for me. I suggest try updating obspy once more. You tested it literally on the day obspy1.3.0 was released and perhaps you caught a tiny glitch that has not been fixed before.

**Comment by wsja** [comment]
@dip16gphy 
Can you check if, in a python console, the following code is returning a list of 8 events?
`
from obspy.clients.fdsn import Client
client = Client()
client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=8)
`
If this is not working, the obspy community is for sure grateful for a bug report, that you could file [here](https://github.com/obspy/obspy/issues).

**Comment by dip16gphy** [comment]
> @dip16gphy Can you check if, in a python console, the following code is returning a list of 8 events?
> 
> ```
> from obspy.clients.fdsn import Client
> client = Client()
> client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=8)
> ```
> 
> If you continue to see the Error above, the obspy community is for sure grateful for a bug report, that you could file [here](https://github.com/obspy/obspy/issues).
> 
> If this is working, please re-run `rfpy_calc`. It should be working just fine.

Sorry for late reply!


The above codes run without any error. But I get something like '<obspy.core.event.catalog.Catalog object at 0x00000124F72B78E0>'

![image](https://user-images.githubusercontent.com/101346054/159177318-cee38b24-cb79-4318-80d0-822df0b1c000.png)

**Comment by wsja** [comment]
I have to admit that I am pretty clueless here, because it is this very call that causes the error in the script. In the same conda environment, `rfpy_calc` should just run. Just to triple check, see if this line throws an error.
```
client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6, maxmagnitude=9)
```
 It is the exact same call that gave you the original error.

**Comment by dip16gphy** [comment]
> client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6, maxmagnitude=9)

Yes, it gives the same error while using the `rfpy_calc` in terminal. 
I checked and found that whenever min magnitude is less than 7, it throws error.

**Comment by wsja** [comment]
Okay, I suspect that there is an ill-formated event in the database that your specific version of obspy cannot handle. I suggest you file a bug report at the obspy site, with the code that produces the error, i.e.:

```
from obspy.clients.fdsn import Client
client = Client()
client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6, minmagnitude=8)
```

To continue testing rfpy, you can run `rfpy_calc` with the option `--minmag 7`

**Comment by dip16gphy** [comment]
> Okay, I suspect that there is an ill-formated event in the database that your specific version of obspy cannot handle. I suggest you file a bug report at the obspy site, with the code that produces the error, i.e.:
> 
> ```
> from obspy.clients.fdsn import Client
> client = Client()
> client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6, minmagnitude=8)
> ```
> 
> To continue testing rfpy, you can run `rfpy_calc` with the option `--minmag 7`

Unfortunately, I am stuck in other error now.
While attempting to open Jupyter Notebook via onda terminal, I am getting this error:
`ImportError: DLL load failed while importing error: %1 is not a valid Win32 application.`

Also, `query_fdsn_stdb -N NY -S MMPY MMPY > logfile` gives following error:
`ImportError: DLL load failed while importing QtWidgets: %1 is not a valid Win32 application.`

I tried reinstallation of pywin32 too, but didn;t work.

**Comment by wsja** [comment]
On Windows 10, there is the possibility to install an Ubuntu-Linux under the hood. Maybe this could be a way around the issue, as much scientific software is developed and maintained on Linux systems. This tutorial might be helpful:

https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by dip16gphy** [comment]
Apart from issue of minmag, all the scripts are running well.

Thanks for help.

**Comment by dip16gphy** [comment]
> Okay, I suspect that there is an ill-formated event in the database that your specific version of obspy cannot handle. I suggest you file a bug report at the obspy site, with the code that produces the error, i.e.:
> 
> ```
> from obspy.clients.fdsn import Client
> client = Client()
> client.get_events(starttime='2013-07-01', endtime='2599-12-31', minmagnitude=6, minmagnitude=8)
> ```
> 
> To continue testing rfpy, you can run `rfpy_calc` with the option `--minmag 7`

I raised this issue of minmagnitude here https://github.com/obspy/obspy/issues/3028#issuecomment-1078235521 .
They gave a solution using 'chunk_length'. I tried & it runs well in python console. 
Now, I want to use this in 'rfpy_calc' script. I am trying the following edits in that but it is still not working. Could you please check & modify the edits?
Thank you!

`# Get catalogue using deployment start and end
        cat = Catalog()
        chunk_length = 365 * 86400  # Query length in seconds
        while tstart <= tend:
                    cat += event_client.get_events(tstart=tstart, tend=tstart + chunk_length, minmagnitude=args.minmag, 
                                maxmagnitude=args.maxmag)
                    tstart += chunk_length`

**Comment by wsja** [comment]
I have implemented this in the master branch. Can you update your installation and try if it solves the issue for you?

**Comment by dip16gphy** [comment]
> Thanks for raising the issue at obspy. The discussion there is quite insightful.
> 
> I have implemented the patch in the master branch. Can you update your installation and try if it solves the issue for you?

Unfortunately it's still not working, throwing the same error. :(



I have one more issue. When rfpy_calc script runs, it shows error retrieving waveforms.
What could be the reason? Is it either because of poor net speed or something else?

**Comment by wsja** [comment]
>  it shows error retrieving waveforms.

This is because some waveforms are actually not on the server. This often happens, as the meta-data of the station (with a single start and end time) often does not account for data gaps. This is not the issue here.

I have added a new commit to master. Please try this one. If the error message persits, please copy it again to this thread for inspection. It is a little easier for me, if you could copy the text directly, instead of taking a screenshot.

Thanks for letting us know and helping making RfPy better!

**Comment by dip16gphy** [comment]
> > it shows error retrieving waveforms.
> 
> This is because some waveforms are actually not on the server. This often happens, as the meta-data of the station (with a single start and end time) often does not account for data gaps. This is not the issue here.
> 
> I have added a new commit to master. Please try this one. If the error message persits, please copy it again to this thread for inspection. It is a little easier for me, if you could copy the text directly, instead of taking a screenshot.
> 
> Thanks for letting us know and helping making RfPy better!

Thanks for quick help.

I have one more query. For some stations, I get this :

`Output Files: RF6E7.csv and RF6E7.pkl

Initializing Client (IRIS)...Done

Querying client...Exception: Cannot complete query or no data in query...`


Is there no recording over these stations or something else?

**Comment by wsja** [comment]
I understand that the recent version of `master` resolved your issue? I am therefore closing this bug.

Unfortunaley, `stdb` hides the true exception behind the exception you are seeing. I tried:

```
from obspy.clients.fdsn import Client
client = Client()
inv = client.get_stations(network='AM', station='RF6E7')
```
and indeed get:
```
FDSNNoDataException: No data available for request
```
which is sad.

However, the FDSN site of the network
http://www.fdsn.org/networks/detail/AM/

shows that the data is also hosted by the Raspberry Shake project and I was able to retrieve waveforms here 
https://fdsnws.raspberryshakedata.com/fdsnws/dataselect/1/builder

I also could get the station information directly via obspy:
```
from obspy.clients.fdsn import Client
client = Client('RASPISHAKE')
inv = client.get_stations(network='AM', station='RF6E7', level='CHANNEL')
```
This indicates that the Channels are name unconvenionally 'EHE", 'EHN' and 'EHZ'. I could at least trigger a call to get some station information via 
```
query_fdsn_stdb -N AM -S RF6E7 -C EH* --Server=RASPISHAKE RF6E7
```
But the resulting files are empty, because the location code is somehow not treated correctly. I do not know what's going wrong there, sorry. You may ask at https://github.com/schaefferaj/StDb. You can reference this issue and I hope Andrew knows a way around this.

As a last resort, you could try using another station nearby, e.g. one from:
```
from obspy.clients.fdsn import Client
client = Client()
inv = client.get_stations(latitude=18.2, longitude=-73.7, maxradius=1, level='channel')
print(inv)
```
I hope that gives you some ideas on how to move on with your project.
